### ISSUE TITLE
Failed to parse XML...Error:syntax error:line1,column0；OSError: [WinError 193] %1 不是有效的 Win32 应用程序

### ISSUE THREAD

**Issue by tangyuan-778** [Weixin-Liang/LLM-scientific-feedback#18]
windows系统下配置了环境，需要的包都有安装好。界面报错如标题所示。
server报错如下：
[2023-10-11 19:15:55,628] ERROR in server:1458: Exception on /api/convert [POST]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\service\blueprints\api.py", line 784, in process_convert_api
    fulltext_processor_config=fulltext_processor_config
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\service\blueprints\api.py", line 701, in _process_pdf_to_response_media_type
    response_media_type
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\app\parser.py", line 524, in get_local_file_for_response_media_type
    return self.get_parsed_layout_document().get_local_file_for_response_media_type(
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\app\parser.py", line 511, in get_parsed_layout_document
    return self.lazy_parsed_layout_document.get()
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\utils\lazy.py", line 31, in get
    self._value = self.factory()
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\app\parser.py", line 499, in _parse_to_parsed_layout_document
    root = etree.parse(self.lazy_alto_xml_path.get())
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\utils\lazy.py", line 31, in get
    self._value = self.factory()
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\app\parser.py", line 491, in _parse_to_alto_xml
    last_page=self.document_request_parameters.last_page
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\external\pdfalto\wrapper.py", line 47, in convert_pdf_to_pdfalto_xml
    with exec_with_logging(command, logging_prefix='pdfalto') as _:
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\site-packages\sciencebeam_parser\utils\background_process.py", line 160, in exec_with_logging
    **kwargs
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\ProgramData\Anaconda3\envs\ScienceBeam\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
[2023-10-11 19:15:55,635] INFO in werkzeug:224: 127.0.0.1 - - [11/Oct/2023 19:15:55] "POST /api/convert HTTP/1.1" 500 -
是否是pdfalto的问题？还是因为其他问题？

**Comment by yuhui-zh15** [comment]
Thanks for your interest in our system. Unfortunately ScienceBeam only supports x86 Linux. Let us know if you find a way to install ScienceBeam on other systems.

**Comment by yuhui-zh15** [comment]
We now added a new system that supports texts as input:

Usage:
```bash
python main_from_text.py  # If you are using non-linux operating systems or want to generate feedback from the parsed paper in text format
```
